### ISSUE TITLE
Lexica Botania is consumed by Alfheim Portal

### ISSUE THREAD

**Issue by unilock** [GTNewHorizons/Botania#40]
As of [v1.10.3-GTNH](https://github.com/GTNewHorizons/Botania/releases/tag/1.10.3-GTNH), when a Lexica Botania is tossed into an active Alfheim Portal, it's consumed instead of being returned with the addition of Elven Knowledge.

To reproduce:
1. Create and activate an Alfheim Portal
2. Toss in a stock Lexica Botania
3. Nothing is returned

**Comment by Felicitas12** [comment]
Botania-1.10.5-GTNH same issue

**Comment by Alastors** [comment]
Fucking Botania and it's throwing items out of blocks

**Comment by Caedis** [comment]
The elves disapprove

**Comment by Glease** [comment]
probably something related to bread explosion cherrypick
