### ISSUE TITLE
java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/Int2IntMap

### ISSUE THREAD

**Issue by Felicitas12** [GTNewHorizons/Botania#48]
Since version 1.10.6-GTNH and above, when you start the game crashes, only on the client, on the server seems to be all right.
On version 1.10.5-GTNH everything was fine.
Crash log: https://hastebin.com/share/riwiwujape.yaml

**Comment by mitchej123** [comment]
You'll need to add/update gtnhlib for fastutils

**Comment by Felicitas12** [comment]
Yes, that helped, thank you
